<?php

/**
 * @file
 * Contains extended_site_information.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function extended_site_information_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the extended_site_information module.
    case 'help.page.extended_site_information':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Override system site settings.') . '</p>';
      return $output;

    default:
  }
}
